name: Run TestCafe tests
on:
  - push
jobs:
  build:
    name: Install Node and launch TestCafe tests in Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: chrome tests
